import { User, Task, NotificationItem, KafkaEvent, EurekaServiceInstance, SystemMetrics } from './types';

export const initialUsers: User[] = [
  {
    id: 'user-mgr-1',
    name: 'YARAMALA SHUBHAROOP AKUL',
    email: 'y.shubharoop@enterprise.com',
    role: 'MANAGER',
    department: 'Engineering & Operations',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    title: 'Lead System Architect & Engineering Manager',
    status: 'ACTIVE',
  },
  {
    id: 'user-mgr-2',
    name: 'Sarah Jenkins',
    email: 'sarah.j@enterprise.com',
    role: 'MANAGER',
    department: 'Product Management',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    title: 'Senior Product Manager',
    status: 'ACTIVE',
  },
  {
    id: 'user-emp-1',
    name: 'Alex Rivera',
    email: 'alex.rivera@enterprise.com',
    role: 'EMPLOYEE',
    department: 'Frontend Development',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    title: 'Senior React Developer',
    status: 'ACTIVE',
  },
  {
    id: 'user-emp-2',
    name: 'Priya Sharma',
    email: 'priya.s@enterprise.com',
    role: 'EMPLOYEE',
    department: 'Backend Services',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    title: 'Spring Boot Microservices Engineer',
    status: 'ACTIVE',
  },
  {
    id: 'user-emp-3',
    name: 'David Chen',
    email: 'david.chen@enterprise.com',
    role: 'EMPLOYEE',
    department: 'DevOps & Cloud',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    title: 'Kafka & Kubernetes Infrastructure Engineer',
    status: 'ACTIVE',
  },
  {
    id: 'user-emp-4',
    name: 'Elena Rostova',
    email: 'elena.r@enterprise.com',
    role: 'EMPLOYEE',
    department: 'QA & Security',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    title: 'Security Auditor & Automation Lead',
    status: 'ACTIVE',
  },
];

export const initialTasks: Task[] = [
  {
    id: 'TSK-1001',
    title: 'Implement Kafka Broker Notification Consumer',
    description: 'Configure the Notification Service Spring Boot listener to subscribe to the `task-assignments` Kafka topic and send real-time push alerts to employees.',
    assignedToId: 'user-emp-2',
    assignedToName: 'Priya Sharma',
    assignedToEmail: 'priya.s@enterprise.com',
    createdById: 'user-mgr-1',
    createdByName: 'YARAMALA SHUBHAROOP AKUL',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    dueDate: new Date(Date.now() + 86400000 * 2).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date().toISOString(),
    category: 'Backend Microservices',
    comments: [
      {
        id: 'cmt-101',
        taskId: 'TSK-1001',
        authorId: 'user-mgr-1',
        authorName: 'YARAMALA SHUBHAROOP AKUL',
        authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        authorRole: 'MANAGER',
        text: 'Hi Priya, please ensure the Kafka listener handles dead-letter queues (DLQ) if the push notification server is temporarily unreachable.',
        timestamp: new Date(Date.now() - 86400000 * 0.8).toISOString(),
      },
      {
        id: 'cmt-102',
        taskId: 'TSK-1001',
        authorId: 'user-emp-2',
        authorName: 'Priya Sharma',
        authorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
        authorRole: 'EMPLOYEE',
        text: 'Understood! I have configured Spring Kafka @RetryableTopic with 3 exponential backoff attempts before routing to the notification-dlq topic.',
        timestamp: new Date(Date.now() - 86400000 * 0.3).toISOString(),
      },
    ],
  },
  {
    id: 'TSK-1002',
    title: 'JWT Authentication Gateway Filter',
    description: 'Develop custom Spring Cloud Gateway filter to validate RSA-signed JWT tokens and inject user roles into downstream HTTP headers.',
    assignedToId: 'user-emp-1',
    assignedToName: 'Alex Rivera',
    assignedToEmail: 'alex.rivera@enterprise.com',
    createdById: 'user-mgr-1',
    createdByName: 'YARAMALA SHUBHAROOP AKUL',
    priority: 'URGENT',
    status: 'SUBMITTED',
    dueDate: new Date(Date.now() + 86400000 * 1).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date().toISOString(),
    submissionNotes: 'Gateway filter completed and validated with Postman suite. PR attached with unit tests achieving 94% coverage.',
    submissionLinks: ['https://github.com/enterprise/gateway-service/pull/42', 'https://postman.co/workspace/jwt-test-results'],
    category: 'Security & Auth',
    comments: [
      {
        id: 'cmt-103',
        taskId: 'TSK-1002',
        authorId: 'user-emp-1',
        authorName: 'Alex Rivera',
        authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        authorRole: 'EMPLOYEE',
        text: 'I submitted the pull request for the Gateway filter. Verified token extraction and X-User-Role header injection.',
        timestamp: new Date(Date.now() - 86400000 * 0.5).toISOString(),
      },
    ],
  },
  {
    id: 'TSK-1003',
    title: 'Setup Eureka Service Discovery Cluster',
    description: 'Deploy 2-node Eureka Service Registry with health check heartbeats for Spring Cloud microservices.',
    assignedToId: 'user-emp-3',
    assignedToName: 'David Chen',
    assignedToEmail: 'david.chen@enterprise.com',
    createdById: 'user-mgr-1',
    createdByName: 'YARAMALA SHUBHAROOP AKUL',
    priority: 'MEDIUM',
    status: 'APPROVED',
    dueDate: new Date(Date.now() - 86400000 * 1).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    submissionNotes: 'Eureka discovery cluster up and running at localhost:8761.',
    reviewFeedback: 'Excellent work David! Heartbeats and failovers tested successfully.',
    category: 'Infrastructure',
  },
  {
    id: 'TSK-1004',
    title: 'Semgrep Static Code Security Analysis',
    description: 'Run Semgrep SAST scans across User Service and Task Service repositories to verify SQL injection and JWT secret exposure compliance.',
    assignedToId: 'user-emp-4',
    assignedToName: 'Elena Rostova',
    assignedToEmail: 'elena.r@enterprise.com',
    createdById: 'user-mgr-1',
    createdByName: 'YARAMALA SHUBHAROOP AKUL',
    priority: 'HIGH',
    status: 'PENDING',
    dueDate: new Date(Date.now() + 86400000 * 4).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: 'Security & QA',
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'user-emp-2',
    title: 'New Task Assigned: Implement Kafka Broker Notification Consumer',
    message: 'Assigned by Manager YARAMALA SHUBHAROOP AKUL. Priority: HIGH.',
    timestamp: new Date(Date.now() - 3600000 * 3).toISOString(),
    read: false,
    taskId: 'TSK-1001',
    type: 'TASK_ASSIGNED',
  },
  {
    id: 'notif-2',
    userId: 'user-mgr-1',
    title: 'Task Submitted for Review: JWT Authentication Gateway Filter',
    message: 'Submitted by Alex Rivera with completion notes and test links.',
    timestamp: new Date(Date.now() - 1800000).toISOString(),
    read: false,
    taskId: 'TSK-1002',
    type: 'TASK_SUBMITTED',
  },
  {
    id: 'notif-3',
    userId: 'user-emp-3',
    title: 'Task Approved: Setup Eureka Service Discovery Cluster',
    message: 'Manager YARAMALA SHUBHAROOP AKUL approved your task submission.',
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    read: true,
    taskId: 'TSK-1003',
    type: 'TASK_REVIEWED',
  },
];

export const initialKafkaEvents: KafkaEvent[] = [
  {
    eventId: 'evt-kfk-101',
    topic: 'task-assignments',
    partition: 0,
    offset: 1042,
    key: 'TSK-1001',
    payload: { taskId: 'TSK-1001', assignedTo: 'user-emp-2', assignedBy: 'user-mgr-1', priority: 'HIGH' },
    timestamp: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    eventId: 'evt-kfk-102',
    topic: 'task-status-updates',
    partition: 1,
    offset: 890,
    key: 'TSK-1002',
    payload: { taskId: 'TSK-1002', oldStatus: 'IN_PROGRESS', newStatus: 'SUBMITTED', updatedBy: 'user-emp-1' },
    timestamp: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    eventId: 'evt-kfk-103',
    topic: 'notification-pushes',
    partition: 0,
    offset: 412,
    key: 'notif-2',
    payload: { targetUserId: 'user-mgr-1', notificationId: 'notif-2', channel: 'WEBSOCKET_PUSH' },
    timestamp: new Date(Date.now() - 1795000).toISOString(),
  },
];

export function getEurekaRegistry(): EurekaServiceInstance[] {
  return [
    {
      id: 'eureka-discovery-server:8761',
      name: 'EUREKA-SERVER',
      status: 'UP',
      host: '127.0.0.1',
      port: 8761,
      database: 'N/A (In-Memory Peer)',
      dbType: 'Eureka Server',
      uptime: '4 days, 12 hours',
      lastHeartbeat: new Date().toISOString(),
      endpoints: ['/eureka/apps', '/actuator/health'],
    },
    {
      id: 'api-gateway-service:8080',
      name: 'API-GATEWAY-SERVICE',
      status: 'UP',
      host: '127.0.0.1',
      port: 8080,
      database: 'Redis Session Cache',
      dbType: 'Spring Cloud Gateway (JWT Auth)',
      uptime: '4 days, 11 hours',
      lastHeartbeat: new Date().toISOString(),
      endpoints: ['/api/auth/**', '/api/tasks/**', '/api/users/**', '/api/notifications/**'],
    },
    {
      id: 'user-service:8081',
      name: 'USER-SERVICE',
      status: 'UP',
      host: '127.0.0.1',
      port: 8081,
      database: 'user_service_db',
      dbType: 'PostgreSQL 16 (pgAdmin)',
      uptime: '4 days, 11 hours',
      lastHeartbeat: new Date().toISOString(),
      endpoints: ['/users', '/roles', '/auth/validate'],
    },
    {
      id: 'main-task-service:8082',
      name: 'MAIN-TASK-SERVICE',
      status: 'UP',
      host: '127.0.0.1',
      port: 8082,
      database: 'main_task_db',
      dbType: 'PostgreSQL 16 (pgAdmin)',
      uptime: '4 days, 11 hours',
      lastHeartbeat: new Date().toISOString(),
      endpoints: ['/tasks', '/tasks/assign', '/tasks/status', '/tasks/review'],
    },
    {
      id: 'notification-service:8083',
      name: 'NOTIFICATION-SERVICE',
      status: 'UP',
      host: '127.0.0.1',
      port: 8083,
      database: 'notification_db',
      dbType: 'PostgreSQL 16 (pgAdmin)',
      uptime: '4 days, 11 hours',
      lastHeartbeat: new Date().toISOString(),
      endpoints: ['/notifications', '/kafka/consumers', '/websocket/push'],
    },
  ];
}

export function computeMetrics(taskList: Task[], userList: User[], eventCount: number): SystemMetrics {
  const total = taskList.length;
  const pending = taskList.filter((t) => t.status === 'PENDING').length;
  const inProgress = taskList.filter((t) => t.status === 'IN_PROGRESS').length;
  const submitted = taskList.filter((t) => t.status === 'SUBMITTED').length;
  const completed = taskList.filter((t) => t.status === 'COMPLETED' || t.status === 'APPROVED').length;
  const overdue = taskList.filter((t) => new Date(t.dueDate) < new Date() && t.status !== 'APPROVED').length;
  const rate = total > 0 ? Math.round((completed / total) * 100) : 0;

  return {
    totalTasks: total,
    pendingTasks: pending,
    inProgressTasks: inProgress,
    submittedTasks: submitted,
    completedTasks: completed,
    overdueTasks: overdue,
    completionRate: rate,
    activeEmployees: userList.filter((u) => u.role === 'EMPLOYEE').length,
    kafkaEventsProcessed: eventCount,
  };
}
